language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: divyakumarjain-github
  github_token:
    secure: "loro7lOd+8yalW+AZ3GJqgNw/LbFF85yf0NQv/fwfl8icwrz+UFn6dPHe/oyVgTGG2KwByyJcttIsiqCsX5AfMvar+y7BB+cdOEzGLozDlyLVMpKA+41ZLYbQcOTCUEYIxmlpcB+JqYMJTP6RjB6ddwSw3HgzLMdGT0Url8ufyHag/JLXXQiO5SgyzOGvdEL6NChKRH7feqjFXio1vzmAYrNGEb1/I4+tjwJDU33STHtx/K+YTbeo7e2bNwJJFJc/g/URiKMAOGT2uuZ3tXHOd6g5hCltVI4uNSn7ZLXHWEhit7GBejGXFhfXW06j/clBwlCi17lpQ066FUGXyWP7nW1VWUa06dXBhTbggYEX6cw2+35aNv5IZxrH8vxCSjMjqvFv4Q0chZawMP+9kx3whnA/VmD4oTWvSDE0ltNHtwtxYl8Uuqvl6Uq9/tMN995IlWp34tpI9P1JmEQkh3M7Yh9p4klFt1s2QWI7DYPqLhWpRRHcz+VBjT1pSFhPaAiIa69KGdtrCfMNswkOZ9LP2Hr5uuzji2baqW5swz8GV57p9zXgmzArEOGLuHtwgymSbsQi90+iF7MF3PEpczdSPwdD9SclYPDE7imXxweMo+uhQFeOQg9e6CrGJYy81P9KqIH/xJLvy5qWWOJsbR/cVbxtTUs2HmeY86q6Xh3ACs="

jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dmaven.test.failure.ignore=true

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email: false
