language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: divyakumarjain-github
  github_token:
    secure: uUvHJtNG6LP0+X1pLMovS4tLiI9OoBqnmTajM1856adukOv5wxEZARnR7SD8zGSDNFTfxBhqT0QY3FHoEqdERYlOfIxwABlyy6kYPlgjMpWAs9ilMTIbDetGpMzThnPfVRzPme+Wffz8TBY9KePS2WK6wfcg6RNDb3PMn30P3PNBw56uW2v1ZmcqUY98XctLvJ31+ljMXnek6XKzUK+NCFKdEmtaMZfsRcVDRtS1xlXm/UXRH3J13uHiiRs4rbR9KIn5bJQ82roerQnf7jBazhTDGxNmPVtYB9HHEOUciW/lpDPyqeW5t4heh0z1nveFsOiskgn4Sh+ora8sxML7MqHv/3sTH26KnoZKd/DGhNiSY+WwuezyOcJ97EK3q9Htl0ZNPjosdlhiaZTGz/3b0nA52ziTnkzJl/joBiGv/ZPmhPXPZtBhSRC3+X5LVks/jOtUMnSpMBEE41eVTsHw8MmQ5YZw/bfeA5d9CNzkuXJzFI4ekqCelfbtk3WODI+faIh/UsuLx/Vz5hrk+SvabEmqrIZMcI116eZHJEJzcTtteJQPpRqElW7j2Ng73VY6YepBQ8eZg/oEsFirM9F8M3gra+i4oQ+33aKFvSIzeX9teNw5D0MoKQ+5b4o7wGd4NmavNNOJe5MFoQvTonh/u600vWypiAOxWYcsghfy6SA=
jdk:
- oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dmaven.test.failure.ignore=true
  - sonar-scanner
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email: false


